In [1]:
import pandas as pd
pd.low_memory = False

### Load and clean scraped data

In [14]:
df1 = pd.read_csv("../data_collection/data_biden/primo_semestre.csv",  lineterminator='\n')
df2 = pd.read_csv("../data_collection/data_biden/secondo_semestre.csv",  lineterminator='\n')
df3 = pd.read_csv("../data_collection/data_biden/terzo_semestre.csv",  lineterminator='\n')
df4 = pd.read_csv("../data_collection/data_biden/quarto_semestre.csv",  lineterminator='\n')
df5 =pd.read_csv("../data_collection/data_biden/quinto_semestre.csv",  lineterminator='\n')

/Users/simonamazzarino/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

### Load and process community DF

In [20]:
df_community1 = pd.read_csv("../data_collection/data_biden/Community_Louvain1.csv", na_filter=True, na_values='[]')
df_community2 = pd.read_csv("../data_collection/data_biden/Community_Louvain2.csv", na_filter=True, na_values='[]')
df_community3 = pd.read_csv("../data_collection/data_biden/Community_Louvain3.csv", na_filter=True, na_values='[]')
df_community4 = pd.read_csv("../data_collection/data_biden/Community_Louvain4.csv", na_filter=True, na_values='[]')
df_community5 = pd.read_csv("../data_collection/data_biden/Community_Louvain5.csv", na_filter=True, na_values='[]')

In [25]:
dict_comm1 = df_community1.to_dict(orient="list")
dict_comm2 = df_community2.to_dict(orient="list")
dict_comm3 = df_community3.to_dict(orient="list")
dict_comm4 = df_community4.to_dict(orient="list")
dict_comm5 = df_community5.to_dict(orient="list")

In [26]:
dict_comm_transformed1 = {user: community for community, users in dict_comm1.items() for user in users}
dict_comm_transformed2 = {user: community for community, users in dict_comm2.items() for user in users}
dict_comm_transformed3 = {user: community for community, users in dict_comm3.items() for user in users}
dict_comm_transformed4 = {user: community for community, users in dict_comm4.items() for user in users}
dict_comm_transformed5 = {user: community for community, users in dict_comm5.items() for user in users}

In [27]:
df_community1 = pd.DataFrame.from_dict(dict_comm_transformed1, orient='index',columns=["community"])
df_community2 = pd.DataFrame.from_dict(dict_comm_transformed2, orient='index',columns=["community"])
df_community3 = pd.DataFrame.from_dict(dict_comm_transformed3, orient='index',columns=["community"])
df_community4 = pd.DataFrame.from_dict(dict_comm_transformed4, orient='index',columns=["community"])
df_community5 = pd.DataFrame.from_dict(dict_comm_transformed5, orient='index',columns=["community"])

In [28]:
df_community1 = df_community1.rename_axis('username').reset_index()
df_community2 = df_community2.rename_axis('username').reset_index()
df_community3 = df_community3.rename_axis('username').reset_index()
df_community4 = df_community4.rename_axis('username').reset_index()
df_community5 = df_community5.rename_axis('username').reset_index()

In [32]:
df_community1['original_community_extension'] = df_community1['community'].map(df_community1['community'].value_counts())
df_community2['original_community_extension'] = df_community2['community'].map(df_community2['community'].value_counts())
df_community3['original_community_extension'] = df_community3['community'].map(df_community3['community'].value_counts())
df_community4['original_community_extension'] = df_community4['community'].map(df_community4['community'].value_counts())
df_community5['original_community_extension'] = df_community5['community'].map(df_community5['community'].value_counts())

In [33]:
df_community1

             username       community  original_community_extension
0            JoeBiden     community_0                           348
1            dmaga101     community_0                           348
2         BarackObama     community_0                           348
3            schatto3     community_0                           348
4                 AOC     community_0                           348
...               ...             ...                           ...
8614   philosogoddess  community_1860                             2
8615          gin_sol  community_1861                             2
8616   BrynnTannehill  community_1861                             2
8617  globalseangmai1  community_1862                             3
8618      Manny_Funes  community_1862                             3

[8619 rows x 3 columns]

### Merge on username

In [34]:
df_nlp1 = (pd.merge(df1, df_community1, left_on='username', right_on='username', how='inner').drop('username', axis=1))
df_nlp2 = (pd.merge(df2, df_community2, left_on='username', right_on='username', how='inner').drop('username', axis=1))
df_nlp3 = (pd.merge(df3, df_community3, left_on='username', right_on='username', how='inner').drop('username', axis=1))
df_nlp4 = (pd.merge(df4, df_community4, left_on='username', right_on='username', how='inner').drop('username', axis=1))
df_nlp5 = (pd.merge(df5, df_community5, left_on='username', right_on='username', how='inner').drop('username', axis=1))

In [35]:
df_nlp1

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,name,place,...,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest,community,original_community_extension
0,0,1218684471211245568,1218684471211245568,2020-01-18 23:59:54+00:00,2020-01-18,23:59:54,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,community_0,348
1,15,1242962294302105600,1242962294302105600,2020-03-25 23:51:18+00:00,2020-03-25,23:51:18,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,community_0,348
2,179,1217165029440552961,1217156937193807872,2020-01-14 19:22:11+00:00,2020-01-14,19:22:11,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'BethLynch2020', 'name': 'eh'...",NaN,NaN,NaN,NaN,community_0,348
3,791,1249384363738796032,1249005745582018560,2020-04-12 18:10:19+01:00,2020-04-12,18:10:19,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'AndyOstroy', 'name': 'Andy O...",NaN,NaN,NaN,NaN,community_0,348
4,1,1218684453494632449,1218663554250727424,2020-01-18 23:59:50+00:00,2020-01-18,23:59:50,100,175711368,Biden is the More Effective Evil,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'number1fan_2', 'name': 'Davi...",NaN,NaN,NaN,NaN,community_55,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39030,884,1264271769285857282,1263964462983380992,2020-05-23 20:07:33+01:00,2020-05-23,20:07:33,100,967032222829162498,roleezj,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'realDonaldTrump', 'name': 'D...",NaN,NaN,NaN,NaN,community_1393,2
39031,898,1264270613486526470,1264253104737980416,2020-05-23 20:02:57+01:00,2020-05-23,20:02:57,100,799343836614885376,Frankie Garcia,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'twostarsartwork', 'name': 'L...",NaN,NaN,NaN,NaN,community_1847,2
39032,935,1264267943069679616,1264233824172548096,2020-05-23 19:52:21+01:00,2020-05-23,19:52:21,100,68697271,Itay Komorovski ðŸ‡®ðŸ‡±,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'Silvergt', 'name': 'DD', 'id...",NaN,NaN,NaN,NaN,community_1584,2
39033,950,1264266065523154946,1263997603693203456,2020-05-23 19:44:53+01:00,2020-05-23,19:44:53,100,901935932122824705,1-65 trump'sCourtRecord,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'BrunoAmato_1', 'name': 'Brun...",NaN,NaN,NaN,NaN,community_1619,2
39034,959,1264265259361153025,1264208610671943680,2020-05-23 19:41:41+01:00,2020-05-23,19:41:41,100,1257055044341555201,legs412,NaN,...,NaN,NaN,NaN,"[{'screen_name': 'PamEllaCasual', 'name': 'Pam...",NaN,NaN,NaN,NaN,community_1247,2

In [36]:
df_nlp1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39035 entries, 0 to 39034
Data columns (total 38 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    39035 non-null  int64
 1   id                            39035 non-null  int64
 2   conversation_id               39035 non-null  int64
 3   created_at                    39035 non-null  object
 4   date                          39035 non-null  object
 5   time                          39035 non-null  object
 6   timezone                      39035 non-null  int64
 7   user_id                       39035 non-null  int64
 8   name                          39035 non-null  object
 9   place                         3 non-null      object
 10  tweet                         39035 non-null  object
 11  language                      39035 non-null  object
 12  mentions                      39035 non-null  object
 13  urls                          39035 non-null  object
 14  photos                        39035 non-null  object
 15  replies_count                 39035 non-null  int64
 16  retweets_count                39035 non-null  int64
 17  likes_count                   39035 non-null  int64
 18  hashtags                      39035 non-null  object
 19  cashtags                      39035 non-null  object
 20  link                          39035 non-null  object
 21  retweet                       39035 non-null  bool
 22  quote_url                     8736 non-null   object
 23  video                         39035 non-null  int64
 24  thumbnail                     6658 non-null   object
 25  near                          0 non-null      float64
 26  geo                           0 non-null      float64
 27  source                        0 non-null      float64
 28  user_rt_id                    0 non-null      float64
 29  user_rt                       0 non-null      float64
 30  retweet_id                    0 non-null      float64
 31  reply_to                      39035 non-null  object
 32  retweet_date                  0 non-null      float64
 33  translate                     0 non-null      float64
 34  trans_src                     0 non-null      float64
 35  trans_dest                    0 non-null      float64
 36  community                     39035 non-null  object
 37  original_community_extension  39035 non-null  int64
dtypes: bool(1), float64(10), int64(10), object(17)
memory usage: 11.4+ MB

In [38]:
del df_nlp1['Unnamed: 0']
del df_nlp2['Unnamed: 0']
del df_nlp3['Unnamed: 0']
del df_nlp4['Unnamed: 0']
del df_nlp5['Unnamed: 0']

In [41]:
df_nlp1.to_csv("df_nlp_com1.csv", index=False)
df_nlp2.to_csv("df_nlp_com2.csv", index=False)
df_nlp3.to_csv("df_nlp_com3.csv", index=False)
df_nlp4.to_csv("df_nlp_com4.csv", index=False)
df_nlp5.to_csv("df_nlp_com5.csv", index=False)

In [42]:
df_nlp1

,id,conversation_id,created_at,date,time,timezone,user_id,name,place,tweet,...,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest,community,original_community_extension
0,1218684471211245568,1218684471211245568,2020-01-18 23:59:54+00:00,2020-01-18,23:59:54,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,#JoeBiden accusing the Sanders campaign of dis...,...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,community_0,348
1,1242962294302105600,1242962294302105600,2020-03-25 23:51:18+00:00,2020-03-25,23:51:18,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,#Bernie is the #AntiTrump #Biden is the #BlueT...,...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,community_0,348
2,1217165029440552961,1217156937193807872,2020-01-14 19:22:11+00:00,2020-01-14,19:22:11,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,@Rosario10i @BethLynch2020 No need to attack h...,...,NaN,NaN,NaN,"[{'screen_name': 'BethLynch2020', 'name': 'eh'...",NaN,NaN,NaN,NaN,community_0,348
3,1249384363738796032,1249005745582018560,2020-04-12 18:10:19+01:00,2020-04-12,18:10:19,100,90497917,David Schor (Biden=#BlueTrump) ðŸ’š,NaN,@AndyOstroy @JoeBiden Hey #Biden supporters: t...,...,NaN,NaN,NaN,"[{'screen_name': 'AndyOstroy', 'name': 'Andy O...",NaN,NaN,NaN,NaN,community_0,348
4,1218684453494632449,1218663554250727424,2020-01-18 23:59:50+00:00,2020-01-18,23:59:50,100,175711368,Biden is the More Effective Evil,NaN,@number1fan_2 @BMarchetich There are 2 other v...,...,NaN,NaN,NaN,"[{'screen_name': 'number1fan_2', 'name': 'Davi...",NaN,NaN,NaN,NaN,community_55,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39030,1264271769285857282,1263964462983380992,2020-05-23 20:07:33+01:00,2020-05-23,20:07:33,100,967032222829162498,roleezj,NaN,@realDonaldTrump @deanbaquet Columbia Univ edu...,...,NaN,NaN,NaN,"[{'screen_name': 'realDonaldTrump', 'name': 'D...",NaN,NaN,NaN,NaN,community_1393,2
39031,1264270613486526470,1264253104737980416,2020-05-23 20:02:57+01:00,2020-05-23,20:02:57,100,799343836614885376,Frankie Garcia,NaN,@TrueBlue100K @twostarsartwork Please.. @JoeBi...,...,NaN,NaN,NaN,"[{'screen_name': 'twostarsartwork', 'name': 'L...",NaN,NaN,NaN,NaN,community_1847,2
39032,1264267943069679616,1264233824172548096,2020-05-23 19:52:21+01:00,2020-05-23,19:52:21,100,68697271,Itay Komorovski ðŸ‡®ðŸ‡±,NaN,@Silvergt @AriFleischer Now after you #Tweet #...,...,NaN,NaN,NaN,"[{'screen_name': 'Silvergt', 'name': 'DD', 'id...",NaN,NaN,NaN,NaN,community_1584,2
39033,1264266065523154946,1263997603693203456,2020-05-23 19:44:53+01:00,2020-05-23,19:44:53,100,901935932122824705,1-65 trump'sCourtRecord,NaN,@BrunoAmato_1 Biden should be more deliberate ...,...,NaN,NaN,NaN,"[{'screen_name': 'BrunoAmato_1', 'name': 'Brun...",NaN,NaN,NaN,NaN,community_1619,2
39034,1264265259361153025,1264208610671943680,2020-05-23 19:41:41+01:00,2020-05-23,19:41:41,100,1257055044341555201,legs412,NaN,@CJ4ShortPlz @PamEllaCasual @jeffsessions @jda...,...,NaN,NaN,NaN,"[{'screen_name': 'PamEllaCasual', 'name': 'Pam...",NaN,NaN,NaN,NaN,community_1247,2